// Copyright (c) 2026, Qalcuity and contributors
// For license information, please see license.txt

frappe.ui.form.on("Qalcuity Tenant", {
	onload(frm) {
		// Set default status for new documents
		if (frm.is_new() && !frm.doc.status) {
			frm.set_value("status", "Active");
		}
	},

	refresh(frm) {
		// Status indicator
		const status_colors = {
			Active: "green",
			Suspended: "orange",
			Terminated: "red",
		};

		if (frm.doc.status) {
			frm.page.set_indicator(
				__(frm.doc.status),
				status_colors[frm.doc.status] || "gray"
			);
		}

		// Action buttons (admin/superadmin only)
		if (!frm.is_new() && !frm.is_dirty()) {
			const can_manage = frappe.user.has_role([
				"System Manager",
				"Qalcuity Superadmin",
				"Qalcuity Admin",
			]);

			if (can_manage) {
				// Suspend active tenant
				if (frm.doc.status === "Active") {
					frm.add_custom_button(
						__("Tangguhkan"),
						function () {
							frappe.confirm(
								__("Tangguhkan tenant '{0}'?", [frm.doc.tenant_id]),
								function () {
									frm
										.call("suspend")
										.then(() => frm.reload_doc());
								}
							);
						},
						__("Actions")
					).addClass("btn-warning");

					// Terminate active tenant (with confirmation)
					frm.add_custom_button(
						__("Hentikan"),
						function () {
							frappe.confirm(
								__(
									"Yakin ingin menghentikan tenant '{0}'? Tindakan ini tidak dapat dibatalkan.",
									[frm.doc.tenant_id]
								),
								function () {
									frm
										.call("terminate")
										.then(() => frm.reload_doc());
								}
							);
						},
						__("Actions")
					).addClass("btn-danger");
				}

				// Reactivate suspended tenant
				if (frm.doc.status === "Suspended") {
					frm.add_custom_button(
						__("Aktifkan Kembali"),
						function () {
							frappe.confirm(
								__("Aktifkan kembali tenant '{0}'?", [frm.doc.tenant_id]),
								function () {
									frm
										.call("reactivate")
										.then(() => frm.reload_doc());
								}
							);
						},
						__("Actions")
					).addClass("btn-success");
				}
			}
		}

		// Show subscription details in dashboard headline
		if (frm.doc.subscription) {
			frappe.call({
				method: "frappe.client.get_value",
				args: {
					doctype: "Qalcuity Subscription",
					fieldname: ["plan", "status", "end_date"],
					filters: { name: frm.doc.subscription },
				},
				callback(r) {
					if (r && r.message) {
						frm.dashboard.set_headline(
							__("Paket: {0} | Status: {1} | Kedaluwarsa: {2}", [
								r.message.plan,
								r.message.status,
								r.message.end_date || "N/A",
							])
						);
					}
				},
			});
		}

		// Show last activity
		if (frm.doc.last_activity) {
			frm.dashboard.add_comment(
				__("Aktivitas Terakhir: {0}", [
					frappe.datetime.str_to_user(frm.doc.last_activity),
				]),
				"gray",
				true
			);
		}

		// Show provisioning date
		if (frm.doc.provisioned_on) {
			frm.dashboard.add_comment(
				__("Provisioned: {0}", [
					frappe.datetime.str_to_user(frm.doc.provisioned_on),
				]),
				"gray",
				true
			);
		}
	},

	customer(frm) {
		// Show info when customer is selected (tenant_id is auto-generated by Python)
		if (frm.doc.customer && !frm.is_new()) {
			// Check if customer already has an active tenant
			frappe.call({
				method: "frappe.client.get_count",
				args: {
					doctype: "Qalcuity Tenant",
					filters: {
						customer: frm.doc.customer,
						status: "Active",
						name: ["!=", frm.doc.name],
					},
				},
				callback(r) {
					if (r && r.message && r.message > 0) {
						frappe.msgprint({
							message: __("Pelanggan ini sudah memiliki {0} tenant aktif.", [
								r.message,
							]),
							indicator: "orange",
						});
					}
				},
			});
		}
	},
});
